### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by dgomes** [dgomes/pyipma#2]
Possible larger list of stations/observations/forecasts:

**Observations**:
http://www.ipma.pt/resources.www/transf/obs-sup/stations.json
http://www.ipma.pt/resources.www/transf/obs-sup/observations.json

**Forecasts**:
http://api.ipma.pt/json/locations.json
http://api.ipma.pt/json/alldata/######.json

**Comment by pjanuario** [comment]
@dgomes I was looking into the code and I think you only look for the districts to get the info right? In my case I see that I have a station really close to me but it's picking the Lisbon one.

**Comment by dgomes** [comment]
Pull requests are welcomed 😄

**Comment by pjanuario** [comment]
In that case, expect a PR with it... probably not that soon... but I will do it since I definitely want my station on the corner! 😄

**Comment by dgomes** [comment]
https://github.com/dgomes/pyipma/commit/80f1990c19d919632e7bce330b9793e1387f4105

Already changed the observations API
